### ISSUE TITLE
Tab switch auto-refocuses keyboard to DGG Chat

### ISSUE THREAD

**Issue by 1VimalS** [DannyAlas/DGG-Everywhere#21] opened 2023-07-06 04:09 UTC
When you go back to the YouTube tab where Destiny's stream is currently being watched, it autofocuses your mouse back to DGG chat even if you weren't focused on it when you got out of the tab.
For example, as a picture-by-picture viewer, sometimes I periodically go back to the stream tab to press one of the keys to rewind/fast-forward 5s/10s for whatever reason. So when I go back to the tab, even when I clicked out of the dgg chat on the right, it puts the key focus back on the chat, meaning if I press J/L/side arrows, it types that onto the chat rather than fast forwarding/rewinding, which is a minor, nonetheless, an inconvenience, where I have to click outside of the DGG screen before pressing my keyboard to rewind or fast forward.

**Comment by DannyAlas** [comment] 2024-01-20 02:21
Duplicate of #20

**Closed as not planned by DannyAlas** 2024-01-20 02:21 UTC
Labels: bug
